export const env = {
	DYNAMO_RECORDS_TABLE: process.env.DYNAMO_RECORDS_TABLE!,
	DYNAMO_UPLOADS_CONTROL_TABLE: process.env.DYNAMO_UPLOADS_CONTROL_TABLE!,
	CONTROL_CHUNKS_QUEUE_URL: process.env.CONTROL_CHUNKS_QUEUE_URL!,
	UPLOADS_BUCKET_TEST_NAME: process.env.UPLOADS_BUCKET_TEST_NAME!,
};
